In [ ]:
! pip list

In [5]:
import random
random.randint(50000,100000)

80960

In [8]:
import statistics


77477.4

In [22]:
salary=[random.randint(50000,100000) for _ in range(10000)]



In [23]:
%%timeit
statistics.mean(salary)


6.71 ms ± 440 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
import numpy as np

In [24]:
%%timeit
np.mean(salary)

625 µs ± 9.94 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [29]:
my_array=np.array([1,2,3,4])
mean_array=my_array.mean()
print(mean_array)

2.5


In [46]:
job_titles=np.array(['Data Analyst','Data Scientist','Data Engineer','Machine Leanring Engineer','AI engineer','AI Engineer'])
base_salaries=np.array([60000,80000,125000,90000,np.nan])
bonus_rates=np.array([.05,.1 , .08 , 0.12, np.nan])

In [37]:
total_salaries=base_salaries* (1+ bonus_rates)
print(total_salaries)


[ 63000.  88000. 135000. 100800.]


In [47]:
total_salaries= base_salaries * (1+ bonus_rates)
print(total_salaries)


[ 63000.  88000. 135000. 100800.     nan]


In [49]:
print(np.nanmean(total_salaries))

96700.0


<span style =" color:green; font-weight:bold;font-size:32px;"> Practise Prompts </span>

In [51]:
# Problem Statement:
# Create a NumPy array representing the number of job applications received each day for a week (7 days). 
# The array should be called applications and contain the following numbers: [10, 15, 7, 20, 25, 30, 5]. 
# Print the array.


applications_list = [10, 15, 7, 20, 25, 30, 5]

applications=np.array(applications_list)

print(applications)



[10 15  7 20 25 30  5]


In [59]:
# Problem Statement:
# Create a NumPy array representing the number of job postings for different job titles called postings.
# The array contains [10, 15, 7, 20, 25, 30, 5]. Use slicing to get the number of postings for the first three job titles.

postings_list = [10, 15, 7, 20, 25, 30, 5]
np_posting_list=np.array(postings_list)

job=np_posting_list[0:3]
print(job)


[10 15  7]


In [63]:
# Problem Statement:
# Create a NumPy array representing the salaries called salaries offered for five different job positions. 
# Calculate the highest and lowest salary using NumPy functions. 

salaries_list = [70000, 85000, 60000, 95000, 80000]

sal_audit=np.array(salaries_list)

high_sal=max(sal_audit)

print(high_sal)

low_sal=min(sal_audit)

print(low_sal)

95000
60000
